### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by robitalec** [robitalec/targets-issa#7]
- [ ] Consider what our general families of functions are and potentially rename functions. How can we rename these functions to form a more coherent set of functions, where we have a category or general group (underscore) specific type or qualifier. I think the extract_distance, extract_pt makes sense, but I think others could use work.
  - prepare_
  - calc_
  - rss_
  - speed_
  - extract_
  - model_
  - plot_
  - predict_
  - resample_

- [ ] Are there functions we don’t need? Are there situations where two functions could be combined by using an argument instead? Eg. plot_boxplot and plot_boxplot_horiz

- [ ]  ?Adjust extract_layers to take arguments “point sample” “distance sample” “buffer sample” (https://github.com/robitalec/targets-issa/blob/main/R/extract_layers.R). Eg. point_sample = list(elevation, land_cover) which internally passes elevation raster and land_cover raster to extract_pt and names columns “point_elevation”. Eg. distance_sample = list(road) which internally passes road feature to extract_distance and names columns “distance_road”

- [ ]  ?Manage if branched targets are NULL in functions (https://github.com/robitalec/targets-issa/blob/main/R/calc_distribution_parameters.R#L5C1-L5C32)

- [ ] Functions that users should adapt to their own needs. (related, can these be generalized?)

  - Plot functions eg. https://github.com/robitalec/targets-issa/blob/main/R/plot_distributions.R
  - Model functions eg. https://github.com/robitalec/targets-issa/blob/main/R/prepare_model.R, https://github.com/robitalec/targets-issa/blob/main/R/model_forest_bin.R
  - Predict eg. https://github.com/robitalec/targets-issa/blob/main/R/predict_h1_forest.R 

- [ ] Reconsider how models are structured in the targets workflow. Should it be a function? Or should it just be inline command for a target?

- [ ] Wrap all of the plots and outputs into a vignette called “results” or “manuscript template”. 

- [ ] Try to parse the model formulas into the manuscript document (see https://cran.r-project.org/web/packages/equatiomatic/index.html) 

- [ ] Use R/variables.R to provide specific place to go to set core “settings” eg. all of these lines (https://github.com/robitalec/targets-issa/blob/main/_targets.R#L35-L58)

- [ ] Convert plot_theme() from a function to a variable in variables.R, I think a function is less intuitive to new users (https://github.com/robitalec/targets-issa/blob/main/R/plot_distributions.R#L8)

- [ ] Document how targets:all works (https://github.com/robitalec/targets-issa/blob/main/_targets.R#L275-L277)

- [ ] Document what each step is doing to highlight what kinds of things need to happen at this stage, to help users adapt to their contexts (https://github.com/robitalec/targets-issa/blob/main/R/prepare_model.R)

- [ ] Document each target and group of targets with inline comments

- [ ] Generally, try to point to external resources eg. iSSA book or papers or amt docs etc throughout the documentation

- [ ] Note to cite the targets-iSSA template in your own work if you worked from it

- [ ] Does this also need to retain the iteration (splitBy) in the output? (https://github.com/robitalec/targets-issa/blob/main/R/model_check.R)

- [ ] Replace raster with terra? Use geotargets? Note if you use geotargets/terra, you can’t return ggplot objects, we need to return saved figures or use base plotting

- [ ] Add roxygen documentation for all functions

- [ ] Make a pkgdown website

- [ ] Make a vignette for adapting the targets template and its functions to your own study
- [ ] https://github.com/robitalec/targets-issa/issues/2
- [ ] https://github.com/robitalec/targets-issa/issues/3
- [ ] https://github.com/robitalec/targets-issa/issues/4
- [ ] https://github.com/robitalec/targets-issa/issues/5
- [ ] Document system requirements from packages eg. gpm
